language: node_js

services:
  - docker

node_js:
  - "8"
  - "10"
cache: npm
script: npm run test:ci
after_success:
  - echo 'Publishing coverage...'
  - npm run coverage:ci

jobs:
  include:
    - stage: npm release
      if: (tag =~ ^v)
      git:
        depth: 1
      node_js: "10"
      before_install:
        - npm i -g makeshift && makeshift -r https://registry.npmjs.org
      script: echo 'Publishing package...'
      deploy:
        provider: npm
        email:
          secure: "NqhgyPgQYZujCp4k4jTIh8QLxetfeLwBKHGQEHTTeYW71glykoZ99lpXpZy7nmVW1Zx4h3F+SHPTfinjxHzfH7AGCJfhpZQrFQOZ4XBiafo5Ht5CCMfbIodl0K6M0RlM/O25o5WmgOGEqnbcjbw1GBHDx2nbKaPymLLWVP8cK2TkHZfNat3t3Lm2mY9iqB2UjNZt3Zk4DUOjngkP8DheJFOSPsRNtkHaOHb2ST2OyivzGMCyt/mmkP7qXu1+SIedvHgpgPYnJXM1Y/SyLDqinir75tYsLHatasXaDwItaLUHYY96eiBZZ2aheWC6R1lwaK8R++N7DKTmuf/yfE/0gihzNF/krE6xBHgqb3knm1zhV1IhxWCeBq5oPLOrjEkc7ms4TSlM3RSfZDa7hdEzDqX9JAXTbhovXXTonkSzASel2q1I9w8T/lDDMOEgMSv8lXRyS6/f3Z9K2za+CmXza+EdvUemGwXiaGC7ISROrZyTWjsSQ1iL6kgGVZ8S6QYDaJ3zQFQ8ZHAduyO7bLsH4mu8MbPRyheIIjdwyhO6kxengz5dXzj4ZNuq3iu6A6OP5CrL+xVdcBX7o7szk/BQJQWtFtQ+fdvN1mBfJXaCqK6+xxqqPhPQywCSy90w2WrqF2YJqR435QbrSajR7wXRsxaHHqTJy7i+3SmgISJkeY8="
        api_key: $NPM_TOKEN
    - stage: docker release
      # Commented out for test purposes
      # if: (tag =~ ^v)
      git:
        depth: 1
      node_js: "10"
      script:
        - echo 'Building Docker image...'
        - docker build -t jormaechea/open-api-mocker .
      deploy:
        provider: script
        script:
          - echo 'Publishing Docker image...'
          - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
          - docker push jormaechea/open-api-mocker
